version: '3'

services:

  database-cryptoportfolio:
    image: 'mysql:8.0.29'
    container_name: database-cryptoportfolio
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=cryptouser
      - MYSQL_PASSWORD=cryptopass
      - MYSQL_DATABASE=cryptoportfolio
      - MYSQL_TCP_PORT=3307
    ports:
      - '3307:3307'
    volumes:
      - ~/devel/private/dockers/mysql_private/data:/var/lib/mysql
