spring:
  application:
    name: cryptoportfolio-service

  datasource:
    url: ${CRYPTOPORTFOLIO_DB_URL:jdbc:mysql://localhost:3307/cryptoportfolio}
    username: ${CRYPTOPORTFOLIO_DB_USERNAME:cryptouser}
    password: ${CRYPTOPORTFOLIO_DB_PASSWORD:cryptopass}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  flyway:
    out-of-order: true
    baselineOnMigrate: true

server:
  port: 8080
  servlet:
    context-path: /cryptoportfolio-service

management:
  server:
    port: 9080
  endpoints:
    web:
      base-path: /api/mgmt
      exposure:
        include: flyway, health, info, metrics

springdoc:
  swagger-ui:
    display-request-duration: true
    operationsSorter: method
    disable-swagger-default-url: true

external-api:
  coin-market-value:
    coinmarketcap:
      pro:
        url: https://pro-api.coinmarketcap.com/v1/cryptocurrency
        api-key: ${COINMARKETCAP_API_KEY}
      sandbox:
        url: https://sandbox-api.coinmarketcap.com/v1/cryptocurrency
        api-key: b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c
